### PR TITLE
Update x/tools

### PR DESCRIPTION
**Pull request by donotnoot**
Fixes this problem:

```
% ~/go/bin/errchkjson ./...
errchkjson: internal error: package "fmt" without types was imported from "(some package)"
```

https://github.com/golang/go/issues/37617

### CODE REVIEW

**Comment by breml** [comment]
Can you please run ´go mod tidy´.

**Comment by donotnoot** [comment]
done

**Comment by donotnoot** [comment]
@breml would you mind tagging a new version so that golangci-lint can update this linter in their next release please?

**Comment by breml** [comment]
done

**Pull request merged**
